const data = [
  {
    id: 1,
    name: "Pepperoni Pizza",
    category: "Main",
    description: "Pepperoni, Mozzarella cheese",
    price: 10,
    image: "/images/pizza.jpg",
    size: { Medium: 0, Large: 5 },
    addOn: { "Extra Cheese": 2, Cheese: 2 },
  },
  {
    id: 2,
    name: "Cheeseburger",
    category: "Main",
    description: "Beef, Comté cheese",
    price: 8,
    image: "/images/burger.jpg",
    size: { Regular: 0, Double: 3 },
    addOn: { Bacon: 1.5 },
  },
  {
    id: 3,
    name: "Italian Salad",
    category: "Salad",
    description: "Radicchio, halved, Cherry tomatoes",
    price: 6,
    image: "/images/salad.jpg",
    size: { Small: 0, Large: 3 },
    addOn: { "Extra Olives": 1 },
  },
  {
    id: 4,
    name: "Coke",
    category: "Drink",
    description: "Coca-Cola",
    price: 2,
    image: "/images/coke.jpg",
    size: { Small: 0, Medium: 1, Large: 2 },
    addOn: { "Lemon Slice": 0.5 },
  },
  {
    id: 5,
    name: "Evian",
    category: "Drink",
    description: "Evian Natural Mineral Water",
    price: 2,
    image: "/images/evian.jpg",
    size: {},
    addOn: {},
  },
  {
    id: 6,
    name: "Margherita Pizza",
    category: "Main",
    description: "Tomato, Mozzarella, Basil",
    price: 9,
    image: "/images/pizza.jpg",
    size: { Medium: 0, Large: 5 },
    addOn: { "Extra Cheese": 2 },
  },
  {
    id: 7,
    name: "Caesar Salad",
    category: "Salad",
    description: "Romaine, Parmesan, Croutons",
    price: 7,
    image: "/images/salad.jpg",
    size: { Small: 0, Large: 3 },
    addOn: { "Grilled Chicken": 3 },
  },
  {
    id: 8,
    name: "Grilled Chicken Sandwich",
    category: "Main",
    description: "Grilled Chicken, Lettuce, Tomato, Mayo",
    price: 7,
    image: "/images/sandwich.jpg",
    size: { Regular: 0, Large: 2 },
    addOn: { Avocado: 1.5 },
  },
  {
    id: 9,
    name: "Lemonade",
    category: "Drink",
    description: "Freshly Squeezed Lemonade",
    price: 3,
    image: "/images/lemonade.jpg",
    size: { Small: 0, Medium: 1, Large: 2 },
    addOn: { Mint: 0.5 },
  },
  {
    id: 10,
    name: "Spaghetti Carbonara",
    category: "Main",
    description: "Spaghetti, Bacon, Eggs, Parmesan",
    price: 12,
    image: "/images/spaghetti.jpg",
    size: { Regular: 0, Large: 4 },
    addOn: { "Extra Bacon": 2 },
  },
];

export default data;
